TCL_BIN=./../../bin_8_6_8/bin/tclsh86.exe

PHONY: tcl array array2 oo

tcl:
	$(TCL_BIN) $@_test.tcl

array:
	$(TCL_BIN) $@_test.tcl
array2:
	$(TCL_BIN) $@_test.tcl
oo:
	$(TCL_BIN) $@_test.tcl
sourcemain:
	$(TCL_BIN) $@_test.tcl