[package]
name = "test_001"
version = "0.1.1"
authors = ["bug00r <bachus@gmx.net>"]
edition = "2018"

[dependencies]


[lib]
name = "test_001"
crate-type = ["staticlib"] # could be `staticlib` and 'dylib' or 'rlib' as well